spring.application.name=Spring-Project-Studia

spring.datasource.url=jdbc:mysql://localhost:3306/note-app-project?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=NoweHaslo123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-unknown-properties=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=AleksanderKozlowski_InformatykaSemestrIV_PS11
jwt.expiration=86400000